apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cluster-nodes-to-clutterstock-http
  namespace: clutterstock-test
spec:
  endpointSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - clutterstock-api
      - clutterstock-frontend
  ingress:
  - fromEntities:
    - host
    - remote-node
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
