apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clutterstock-api
  namespace: clutterstock-test
spec:
  podSelector:
    matchLabels:
      app: clutterstock-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability-production
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
          except:
            - 169.254.169.254/32
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clutterstock-frontend
  namespace: clutterstock-test
spec:
  podSelector:
    matchLabels:
      app: clutterstock-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: clutterstock-test
        - podSelector:
            matchLabels:
              app: clutterstock-api
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: shared-test
        - podSelector:
            matchLabels:
              app: redis
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
          except:
            - 169.254.169.254/32
