apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-platform-production.yaml
- ceph-csi
- cert-manager
- traefik
- authelia-production
- headlamp-production
- dex-example-app-production
- oidc-k8s-admins-rbac
- policy-reporter-production
- kubescape-production
- observability
- homepage
- shared/production
- shared/test
- rabbitmq-production
- clutterstock
- clutterstock-test
- test-test
- ingress.yaml
- hubble-ui-ingress.yaml
