apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clutterstock-api-sqlite
  namespace: test
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
