services:
  dump1090-fa:
    image: ${DOCKER_REGISTRY}sdr/adsb/dump1090-fa-wsh:0.1.0
    container_name: dump1090-fa
    volumes:
      - dump1090-fa-data:/run/dump1090-fa
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - "c 189:* rwm"
    environment:
      DEVICE_TYPE: rtlsdr
      DEVICE_INDEX: 00001090
      LAT: ${LAT}
      LON: ${LON}
      EXTRA_ARGS: --quiet --wisdom /opt/dump1090-fa/wisdom.rpi3b
    restart: always

  tar1090:
    image: ${DOCKER_REGISTRY}sdr/adsb/tar1090-wsh:0.1.0
    container_name: tar1090
    depends_on:
      dump1090-fa:
        condition: service_healthy
    volumes:
      - dump1090-fa-data:/run/dump1090-fa
    environment:
      AISCATCHER_SERVER: ${AISCATCHER_SERVER}
      AISCATCHER_REFRESH: 15
      HEYWHATSTHAT_ID: ${HEYWHATSTHAT_ID}
    restart: always

  piaware:
    image: ${DOCKER_REGISTRY}sdr/adsb/piaware-wsh:0.1.0
    container_name: piaware
    depends_on:
      dump1090-fa:
        condition: service_healthy
    environment:
      LAT: ${LAT}
      LON: ${LON}
      FEEDER_ID: ${PIAWARE_FEEDER_ID}
      RECEIVER_HOST: localhost
      # RECEIVER_TYPE: other
      # RECEIVER_HOST: dump1090-fa
      # RECEIVER_PORT: 30005
      # MLAT_BEAST_HOST: dump1090-fa
      # MLAT_BEAST_PORT: 30104
      SKYAWARE_URL: ${SKYAWARE_URL}
      # DEBUG: true
    restart: always

  fr24:
    image: ${DOCKER_REGISTRY}sdr/adsb/fr24-wsh:0.1.0
    container_name: fr24
    depends_on:
      dump1090-fa:
        condition: service_healthy
    environment:
      FR24_KEY: ${FR24_KEY}
      # RECEIVER_TYPE: avr-tcp
      # RECEIVER_HOST: dump1090-fa
      # RECEIVER_PORT: 30002
    restart: always

  adsbexchange:
    image: ${DOCKER_REGISTRY}sdr/adsb/adsbexchange-wsh:0.1.0
    container_name: adsbexchange
    depends_on:
      dump1090-fa:
        condition: service_healthy
    # volumes:
    #   - dump1090-fa-data:/run/dump1090-fa
    environment:
      LAT: ${LAT}
      LON: ${LON}
      # RECEIVER_HOST: dump1090-fa
      # RECEIVER_PORT: 30005
      # MLAT_BEAST_HOST: dump1090-fa
      # MLAT_BEAST_PORT: 30104
      ADSBX_UUID: ${ADSBX_UUID}
    restart: always

  opensky:
    image: ${DOCKER_REGISTRY}sdr/adsb/opensky-wsh:0.1.0
    container_name: opensky
    depends_on:
      dump1090-fa:
        condition: service_healthy
    environment:
      LAT: ${LAT}
      LON: ${LON}
      ALT: ${ALT}
      OPENSKY_USERNAME: ${OPENSKY_USERNAME}
      OPENSKY_SERIAL: ${OPENSKY_SERIAL}
      # RECEIVER_HOST: dump1090-fa
      # RECEIVER_PORT: 30005
      # OPENSKY_DEVICE_TYPE: default
    restart: always

volumes:
  dump1090-fa-data:
