apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: shared-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
        app.kubernetes.io/name: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: docker.io/redis/redisinsight:3.2.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 5540
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
            - name: RI_PROXY_PATH
              value: "/"
            - name: RI_REDIS_HOST
              value: "redis"
            - name: RI_REDIS_PORT
              value: "6379"
            - name: RI_REDIS_ALIAS
              value: "Default-Redis"
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: shared-production
spec:
  type: ClusterIP
  ports:
    - port: 5540
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: redisinsight
