apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-platform-edge-sdr.yaml
- traefik
- ceph-csi
- kubescape-edge-sdr
- policy-reporter-edge-sdr
- homepage
- headlamp-edge-sdr
- podinfo-edge-sdr
- ais-catcher-edge-sdr
- adsb-edge-sdr
- fluent-bit-edge-sdr
- node-exporter-edge-sdr
- prometheus-agent-edge-sdr
- ingress.yaml
