apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-platform-edge-sdr.yaml
  - traefik
  - ceph-csi
  - kubescape-edge-sdr
  - policy-reporter-edge-sdr
  - homepage
  - headlamp-edge-sdr
  - podinfo-edge-sdr
  - ingress.yaml
