apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.20.1/cluster-operator.yml
  - messaging-topology-operator-no-namespace.yaml
  - namespace.yaml
  - certificate-rabbitmq-tls.yaml
  - rabbitmq-cluster.yaml
  - topology-vhost-test-test.yaml
  - topology-user-test-api.yaml
  - topology-permission-test-api.yaml
  - networkpolicy-rabbitmq.yaml
  - cilium-cluster-nodes-to-rabbitmq-management.yaml
  - rabbitmq-management-ingress.yaml
