# Username must match Secret clutterstock-prod-rabbitmq-credentials key "username".
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: clutterstock-prod-prod
  namespace: rabbitmq-production
spec:
  vhost: prod
  user: clutterstock-prod
  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
