# Username must match Secret clutterstock-test-rabbitmq-credentials key "username".
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: clutterstock-test-test
  namespace: rabbitmq-production
spec:
  vhost: test
  user: clutterstock-test
  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
