# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "github-actions"
  directories:
  - "/"
  open-pull-requests-limit: 20
  target-branch: "main"
  schedule:
    interval: "weekly"
    day: "monday"
  cooldown:
    default-days: 7

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7

- package-ecosystem: "docker"
  directories:
  - "/compose/templates/adsb/adsbexchange"
  - "/compose/templates/adsb/dump1090-fa"
  - "/compose/templates/adsb/fr24"
  - "/compose/templates/adsb/opensky"
  - "/compose/templates/adsb/piaware"
  - "/compose/templates/adsb/tar1090"
  - "/compose/templates/ais/ais-catcher"
  - "/compose/templates/sdr-base/bookworm/base-image"
  - "/compose/templates/sdr-base/bookworm/build-image"
  - "/compose/templates/sdr-base/bullseye/base-image"
  - "/compose/templates/sdr-base/bullseye/build-image"
  - "/compose/templates/sdr-base/buster/base-image"
  - "/compose/templates/sdr-base/buster/build-image"
  - "/clusters/test-deployment"
  - "/clusters/test-deployment/apps"
  - "/clusters/test-deployment/apps/clutterstock-migrate"
  - "/clusters/test-deployment/apps/homepage"
  - "/clusters/test-deployment/apps/kubevious"
  - "/clusters/test-deployment/apps/observability"
  - "/clusters/test-deployment/flux-system"
  - "/clusters/production"
  - "/clusters/production/apps"
  - "/clusters/production/apps/ceph-csi"
  - "/clusters/production/apps/clutterstock-migrate"
  - "/clusters/production/apps/homepage"
  - "/clusters/production/apps/observability"
  - "/clusters/production/apps/traefik"
  - "/clusters/production/flux-system"
  schedule:
    interval: "daily"

- package-ecosystem: "docker-compose"
  directories:
  - "/compose/templates/adsb"
  - "/compose/templates/ais"
  - "/compose/templates/sdr-base"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker-compose"
  directories:
  - "/compose/servers/radio-pi01/ais"
  - "/compose/servers/radio-pi01/adsb"
  assignees: [ "hwinther" ]
  target-branch: "deploy/radio-pi01"
  schedule:
    interval: "daily"

- package-ecosystem: "docker-compose"
  directories:
  - "/compose/servers/radio-pi02/ais"
  - "/compose/servers/radio-pi02/adsb"
  assignees: [ "hwinther" ]
  target-branch: "deploy/radio-pi02"
  schedule:
    interval: "daily"
