apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-authelia-production.yaml
  - helmrepository.yaml
  - configmap-authelia-users.yaml
  - secret-authelia-oidc-jwks.yaml
  - authelia-helmrelease.yaml
  - cilium-cluster-nodes-to-authelia-http.yaml
