apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: obs-otel-collector
  namespace: test
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: obs-prometheus
      namespace: test
    - name: obs-loki
      namespace: test
    - name: obs-tempo
      namespace: test
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.147.1"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: test
  values:
    mode: deployment
    replicaCount: 1
    fullnameOverride: obs-otel-collector
    image:
      repository: otel/opentelemetry-collector-contrib
    command:
      name: otelcol-contrib
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
    ports:
      jaeger-compact:
        enabled: false
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
        enabled: false
      metrics:
        enabled: true
    alternateConfig:
      extensions:
        health_check:
          endpoint: ${env:MY_POD_IP}:13133
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318
      processors:
        batch: {}
        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25
      exporters:
        otlp:
          endpoint: obs-tempo.test.svc.cluster.local:4317
          tls:
            insecure: true
        otlphttp:
          endpoint: http://obs-prometheus-server.test.svc.cluster.local/api/v1/otlp
          tls:
            insecure: true
        loki:
          endpoint: http://obs-loki-gateway.test.svc.cluster.local/loki/api/v1/push
          tls:
            insecure: true
      service:
        telemetry:
          metrics:
            readers:
              - pull:
                  exporter:
                    prometheus:
                      host: ${env:MY_POD_IP}
                      port: 8888
        extensions:
          - health_check
        pipelines:
          traces:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [otlp]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [otlphttp]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [loki]
