# The purpose of this compose file is to simplify building all the base and build images for local use or testing

services:
  sdr-base:
    build:
      context: bookworm/base-image
    image: ${DOCKER_REGISTRY}sdr/sdr-base-wsh:bookworm
    deploy:
      replicas: 0

  sdr-build:
    build:
      context: bookworm/build-image
    image: ${DOCKER_REGISTRY}sdr/sdr-build-wsh:bookworm
    deploy:
      replicas: 0

  sdr-base-bullseye:
    build:
      context: bullseye/base-image
    image: ${DOCKER_REGISTRY}sdr/sdr-base-wsh:bullseye
    deploy:
      replicas: 0

  sdr-build-bullseye:
    build:
      context: bullseye/build-image
    image: ${DOCKER_REGISTRY}sdr/sdr-build-wsh:bullseye
    deploy:
      replicas: 0

  sdr-base-buster:
    build:
      context: buster/base-image
    image: ${DOCKER_REGISTRY}sdr/sdr-base-wsh:buster
    deploy:
      replicas: 0

  sdr-build-buster:
    build:
      context: buster/build-image
    image: ${DOCKER_REGISTRY}sdr/sdr-build-wsh:buster
    deploy:
      replicas: 0
