#cloud-config
chpasswd:
  expire: False
users:
- default
- name: root
  lock_passwd: false
  #hashed_passwd: "root-hashed-password"
  ssh_redirect_user: false
  ssh_authorized_keys:
  - ssh-public-key-here
- name: user
  gecos: user
  groups: adm, users, sudo, docker
  lock_passwd: false
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  #passwd: "user-hashed-password"
  ssh_authorized_keys:
  - ssh-public-key-here
