apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- kyverno-rbac-clone-source-secrets.yaml
- cluster.yaml
- cluster-cluttertestdb.yaml
- networkpolicy-cnpg.yaml
- networkpolicy-cnpg-cluttertestdb.yaml
- networkpolicy-adminer.yaml
- networkpolicy-oauth2-proxy-adminer.yaml
- adminer-deployment.yaml
- adminer-service.yaml
- oauth2-proxy-adminer-deployment.yaml
- oauth2-proxy-adminer-service.yaml
- adminer-ingress.yaml
- cilium-cluster-nodes-to-adminer-http.yaml
- cilium-networkpolicy-cnpg-apiserver.yaml
- kyverno-clusterpolicy-clone-testdb-app.yaml
- kyverno-clusterpolicy-clone-cluttertestdb-app.yaml
