apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- home-assistant-statefulset.yaml
- traefik-middleware-authelia-forwardauth.yaml
- home-assistant-ingress.yaml
- cilium-cluster-nodes-to-http.yaml
