apiVersion: apps/v1
kind: Deployment
metadata:
  name: clutterstock-api
  namespace: clutterstock-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clutterstock-api
  template:
    metadata:
      labels:
        app: clutterstock-api
        app.kubernetes.io/name: clutterstock-api
    spec:
      containers:
        - name: clutterstock-api
          image: ghcr.io/hwinther/clutterstock/api:0.9.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ConnectionStrings__ClutterStock
              value: Data Source=/data/clutterstock.db
            - name: OTEL_SERVICE_NAME
              value: "clutterstock-api"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://obs-otel-collector.observability-production.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=clutterstock-production,deployment.environment=production
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: sqlite-data
              mountPath: /data
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: clutterstock-api-sqlite
---
apiVersion: v1
kind: Service
metadata:
  name: clutterstock-api
  namespace: clutterstock-production
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: clutterstock-api
