apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- kyverno-rbac-generate-postgres-prod-app-secret.yaml
- clutterstock-api-deployment.yaml
- clutterstock-frontend-deployment.yaml
- networkpolicies.yaml
- cilium-cluster-nodes-to-http.yaml
patches:
- path: clutterstock-api-strategy-patch.yaml
