apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterpolicy-github-slsa-provenance.yaml
- clusterpolicy-cyclonedx-sbom.yaml
- clusterpolicy-cosign-vuln-attestation.yaml
