apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterissuer-letsencrypt-dns.yaml
- clusterissuer-selfsigned-bootstrap.yaml
- certificate-internal-ca.yaml
- clusterissuer-internal-ca.yaml
- bundle-wsh-internal-ca.yaml
