apiVersion: apps/v1
kind: Deployment
metadata:
  name: clutterstock-api
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clutterstock-api
  template:
    metadata:
      labels:
        app: clutterstock-api
    spec:
      containers:
      - name: clutterstock-api
        image: ghcr.io/hwinther/clutterstock/api:0.5.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: OTEL_SERVICE_NAME
          value: "clutterstock-api"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://obs-otel-collector.test.svc.cluster.local:4317"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: clutterstock-api
  namespace: test
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: clutterstock-api
