name: Publish dump1090-fa docker image

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/adsb/build-dump1090-fa.yaml"
      - "compose/templates/adsb/dump1090-fa/**"

permissions:
  packages: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PACKAGE_NAME: dump1090-fa-wsh
  PACKAGE_DESCRIPTION: "ADSB Exchange feeder for WSH"
  PACKAGE_VENDOR: WSH
  WORKING_DIRECTORY: compose/templates/adsb/dump1090-fa

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push docker image
        uses: ./.github/actions/docker
        with:
          package_name: ${{ env.PACKAGE_NAME }}
          package_description: ${{ env.PACKAGE_DESCRIPTION }}
          package_vendor: ${{ env.PACKAGE_VENDOR }}
          working_directory: ${{ env.WORKING_DIRECTORY }}
          push_condition: ${{ github.event_name != 'pull_request' }}
          latest_tag_enabled: "true"
