services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    privileged: false
    command:
      - bash
      - "-c"
      - "chmod 600 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_stream; rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
      - "15675:15675"
      - "5552:5552"
      - "15692:15692"
    volumes:
      - "./docker-volumes/rabbitmq/data/:/var/lib/rabbitmq/mnesia"
      - "./docker-volumes/rabbitmq/log/:/var/log/rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitcookie
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: todo-replace-me
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
