apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-reporter-ui
  namespace: policy-reporter-production
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: headlamp-production-authelia-forwardauth@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Management
    gethomepage.dev/name: Policy Reporter
    gethomepage.dev/icon: mdi-clipboard-text-search
    gethomepage.dev/description: Kyverno policy reports dashboard
spec:
  rules:
  - host: policy-reporter.mgmt.wsh.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: policy-reporter-ui
            port:
              number: 8080
