apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: clutterstock-preview-pr-260
  namespace: postgres-test
spec:
  name: clutterstock_pr260
  owner: app
  cluster:
    name: cluttertestdb
  databaseReclaimPolicy: delete
  ensure: present
