apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterpolicy-disallow-privilege-escalation.yaml
  - clusterpolicy-require-run-as-non-root.yaml
  - clusterpolicy-require-resource-limits.yaml
