apiVersion: apps/v1
kind: Deployment
metadata:
  name: wshno
  namespace: wshno-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wshno
  template:
    metadata:
      labels:
        app: wshno
        app.kubernetes.io/name: wshno
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: wshno
        image: ghcr.io/wshno/wshno/web:0.3.0@sha256:ace62de331524b7e4249b6fc520464c362a812dcf94eed9dc50896b90658ab35
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wshno
  namespace: wshno-production
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: wshno
