apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- kyverno-rbac-clone-source-secrets.yaml
- cluster-clutterstockdb.yaml
- networkpolicy-cnpg-clutterstockdb.yaml
- networkpolicy-adminer.yaml
- networkpolicy-oauth2-proxy-adminer.yaml
- adminer-deployment.yaml
- adminer-service.yaml
- oauth2-proxy-adminer-deployment.yaml
- oauth2-proxy-adminer-service.yaml
- adminer-ingress.yaml
- cilium-cluster-nodes-to-adminer-http.yaml
- kyverno-clusterpolicy-clone-clutterstockdb-app.yaml
