apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- kyverno-rbac-clone-source-secrets.yaml
- cluster-postgres-prod.yaml
- database-authelia.yaml
- networkpolicy-cnpg-postgres-prod.yaml
- cilium-networkpolicy-cnpg-apiserver.yaml
- networkpolicy-adminer.yaml
- networkpolicy-oauth2-proxy-adminer.yaml
- adminer-deployment.yaml
- adminer-service.yaml
- oauth2-proxy-adminer-deployment.yaml
- oauth2-proxy-adminer-service.yaml
- adminer-ingress.yaml
- cilium-cluster-nodes-to-adminer-http.yaml
- kyverno-clusterpolicy-clone-postgres-prod-app.yaml
