apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-adminer
  namespace: postgres-production
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy-adminer
  ports:
  - name: http
    port: 4180
    targetPort: http
    protocol: TCP
