apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace-dex-example-app-production.yaml
- kyverno-policyexception-dex-example-app-images.yaml
- dex-example-app-deployment.yaml
- dex-example-app-service.yaml
- dex-example-app-ingress.yaml
- networkpolicies.yaml
- cilium-cluster-nodes-to-dex-example-http.yaml
