apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- mosquitto-configmap.yaml
- mosquitto-statefulset.yaml
- mosquitto-podmonitor.yaml
- cilium-mqtt-ingress.yaml
- kyverno-rbac-generate-pbs-encryption-keyfile.yaml
- mosquitto-pbs-backup-cronjob.yaml
- mqttui-deployment.yaml
- traefik-middleware-authelia-forwardauth.yaml
- mqttui-ingress.yaml
- cilium-cluster-nodes-to-mqttui-http.yaml
