apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - redis-deployment.yaml
  - test-api-deployment.yaml
  - test-frontend-deployment.yaml
  - test-ingress.yaml
