apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  namespace: test-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
        app.kubernetes.io/name: test-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
        runAsGroup: 1654
        fsGroup: 1654
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: test-api
        image: ghcr.io/hwinther/test/api:0.64.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__Blogging
          value: "Server=sqlserver,1433;Initial Catalog=api;User=sa;Password=DevelopmentOnlyPassword1;TrustServerCertificate=True;"
        - name: OTEL_SERVICE_NAME
          value: "test-api"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://obs-otel-collector.observability-production.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: RabbitMq__HostName
          value: "rabbitmq.rabbitmq-production.svc.cluster.local"
        - name: RabbitMq__VirtualHost
          value: "test-test"
        - name: RabbitMq__UserName
          valueFrom:
            secretKeyRef:
              name: test-api-rabbitmq
              key: username
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: test-api-rabbitmq
              key: password
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: test-test
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: test-api
