apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clutterstock-api-sqlite
  namespace: clutterstock-test
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
