name: Publish sdr-base docker images

on:
  workflow_dispatch:
  push:
    branches: ["main", "feat/update-adsb"]
    paths:
      - ".github/workflows/build-sdr-base-images.yaml"
      - "compose/templates/sdr-base/**"

permissions:
  packages: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PACKAGE_NAME: sdr-base-build
  PACKAGE_DESCRIPTION: "SDR base build image for WSH"
  PACKAGE_VENDOR: WSH
  WORKING_DIRECTORY: compose/templates/sdr-base

jobs:
  publish-docker-image:
    strategy:
      matrix:
        debian_release: ["bookworm", "bullseye"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push docker image
        uses: ./.github/actions/docker
        with:
          package_name: ${{ env.PACKAGE_NAME }}
          package_description: "${{ env.PACKAGE_DESCRIPTION }} (for ${{ matrix.debian_release }})"
          package_vendor: ${{ env.PACKAGE_VENDOR }}
          working_directory: ${{ env.WORKING_DIRECTORY }}/${{ matrix.debian_release }}-build
          push_condition: ${{ github.event_name != 'pull_request' }}
          tag: ${{ matrix.debian_release }}
