name: Publish docker image

on:
  workflow_dispatch:
  push:
    branches: ["main", "feat/ais-package"]
    paths:
      - ".github/workflows/docker.yaml"
      - "compose/templates/ais/ais-catcher"

permissions:
  # for ghcr.io (docker registry):
  packages: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Container Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ais-test
          tags: |
            type=edge,branch=main
            type=ref,event=tag

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images
        uses: docker/build-push-action@v5
        with:
          context: "compose/templates/ais/ais-catcher"
          platforms: linux/amd64, linux/arm64, linux/arm64/v8
          push: true
          #push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build the docker image
      #   run: |
      #     tag=ghcr.io/hwinther/wsh-pve/pve-build:12
      #     tag_latest=ghcr.io/hwinther/wsh-pve/pve-build:latest
      #     echo tag=$tag tag_latest=$tag_latest
      #     docker build . -t $tag -t $tag_latest -f build.Dockerfile
      #     docker push $tag
      #     docker push $tag_latest
